### ISSUE TITLE
Roadmap for version 1.0

### ISSUE THREAD

**Issue by duongdev** [duongdev/ctg-canteen#55]
# Chức năng chính

- [ ] Quản lý học sinh.
- [ ] Quản lý món ăn.
- [ ] Quản lý thực đơn.
- [ ] Quản lý đăng ký ăn.
- [ ] Quản lý danh sách học sinh đăng ký ăn.

# Quản lý học sinh

- [ ] Import danh sách học sinh từ file excel theo mẫu sẵn có.
- [ ] Người dùng dùng tên đăng nhập + mật khẩu được tạo sẵn để đăng nhập hệ thống.
- [ ] Người dùng có thể thay đổi mật khẩu.
- [ ] Admin có thể reset mật khẩu của người dùng bất kì.
- [ ] Admin có thể khoá tài khoản người dùng bất kì.

# Quản lý món ăn

- [ ] Admin có thể tạo thêm, sửa, vô hiệu hoá món ăn. Mỗi món ăn bao gồm các thông tin như tên, mô tả, hình ảnh, giá, các buổi ăn khả dụng, ...

# Quản lý đăng kí

- [ ] Admin có thể tạo các đợt đăng ký với kì hạn đăng ký.
- [ ] Admin có thể add các món ăn vào các buổi ăn.
- [ ] Học sinh đăng ký các buổi ăn, món ăn khi có đợt đăng ký mới được mở.
- [ ] Báo cáo đợt đăng ký theo danh sách phần ăn mỗi buổi ăn (cho bếp).
- [ ] Báo cáo đợt đăng ký theo số tiền mỗi học sinh phải thanh toán cho mỗi đợt đăng ký ăn.
- [ ] Kết thúc mỗi ngày ăn, admin có thể upload danh sách chấm công bằng file excel.
- [ ] Báo cáo danh sách học sinh bỏ ăn theo mỗi ngày dựa trên danh sách chấm công.

**Comment by nguyenthienthanh** [comment]
Ok. How about plan?
How many hour we will spend on this project?
I can spend about 6 hours per week
@duongdev

**Comment by lamvh** [comment]
Quản lý món ăn: chay, mặn, default
